version: '2'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: musicloud
      POSTGRES_USER: musicloud
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_HOSTNAME: db
      DB_DATABASE: musicloud
      DB_USERNAME: musicloud
      DB_PASSWORD: musicloud
    volumes:
      - .:/usr/app/
    depends_on:
      - db
