version: '3'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: musicloud
      POSTGRES_USER: musicloud
    volumes:
      - ./docker/001-init.sql:/docker-entrypoint-initdb.d/001-init.sql
      - ./docker/002-guest.sql:/docker-entrypoint-initdb.d/002-guest.sql
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_HOSTNAME: db
      DB_DATABASE: musicloud
      DB_USERNAME: musicloud
      DB_PASSWORD: musicloud
    volumes:
      - .:/usr/app/
    links:
      - db
